<?php

namespace App\Enums;

class HazardStatement
{
    public static function list(): array
    {
        return [
            // FIZIČKE OPASNOSTI
            "H200" => "H200 – Nestabilni eksplozivi.",
            "H201" => "H201 – Eksplozivno; opasnost od eksplozije ogromnih razmjera.",
            "H202" => "H202 – Eksplozivno; velika opasnost od rasprskavanja.",
            "H203" => "H203 – Eksplozivno; opasnost od vatre, udarnog vala ili rasprskavanja.",
            "H204" => "H204 – Opasnost od vatre ili rasprskavanja.",
            "H205" => "H205 – U vatri može izazvati eksploziju ogromnih razmjera.",
            "H206" => "H206 – Opasnost od vatre, udarnog vala ili rasprskavanja; povećan rizik od eksplozije ako je smanjen udio desenzitirajućeg agensa.",
            "H207" => "H207 – Opasnost od vatre ili rasprskavanja; povećan rizik od eksplozije ako je smanjen udio desenzitirajućeg agensa.",
            "H208" => "H208 – Opasnost od vatre; povećan rizik od eksplozije ako je smanjen udio desenzitirajućeg agensa.",
            "H220" => "H220 – Vrlo lako zapaljivi plin.",
            "H221" => "H221 – Zapaljivi plin.",
            "H222" => "H222 – Vrlo lako zapaljivi aerosol.",
            "H223" => "H223 – Zapaljivi aerosol.",
            "H224" => "H224 – Vrlo lako zapaljiva tekućina i para.",
            "H225" => "H225 – Lako zapaljiva tekućina i para.",
            "H226" => "H226 – Zapaljiva tekućina i para.",
            "H228" => "H228 – Zapaljiva krutina.",
            "H229" => "H229 – Spremnik pod tlakom: može se rasprsnuti ako se grije.",
            "H230" => "H230 – Može eksplozivno reagirati i bez prisustva zraka.",
            "H231" => "H231 – Može eksplozivno reagirati i bez prisustva zraka na povišenom tlaku i/ili temperaturi.",
            "H232" => "H232 – Može se spontano zapaliti u dodiru sa zrakom.",
            "H240" => "H240 – Zagrijavanje može uzrokovati eksploziju.",
            "H241" => "H241 – Zagrijavanje može uzrokovati požar ili eksploziju.",
            "H242" => "H242 – Zagrijavanje može uzrokovati požar.",
            "H250" => "H250 – Samozapaljivo u dodiru sa zrakom.",
            "H251" => "H251 – Samozagrijavanje; može se zapaliti.",
            "H252" => "H252 – Samozagrijavanje u velikim količinama; može se zapaliti.",
            "H260" => "H260 – U dodiru s vodom oslobađa zapaljive plinove koji se mogu spontano zapaliti.",
            "H261" => "H261 – U dodiru s vodom oslobađa zapaljive plinove.",
            "H270" => "H270 – Može uzrokovati ili pojačati požar; oksidans.",
            "H271" => "H271 – Može uzrokovati požar ili eksploziju; jaki oksidans.",
            "H272" => "H272 – Može pojačati požar; oksidans.",
            "H280" => "H280 – Sadrži stlačeni plin; zagrijavanje može uzrokovati eksploziju.",
            "H281" => "H281 – Sadrži pothlađeni, ukapljeni plin; može uzrokovati kriogene opekline ili ozljede.",
            "H290" => "H290 – Može nagrizati metale.",

            // ZDRAVSTVENE OPASNOSTI
            "H300" => "H300 – + H310 + H330 Smrtonosno ako se proguta, u dodiru s kožom ili ako se udiše.",
            "H301" => "H301 – + H311 + H331 Otrovno ako se proguta, u dodiru s kožom ili ako se udiše.",
            "H302" => "H302 – + H312 + H332 Štetno ako se proguta, u dodiru s kožom ili ako se udiše.",
            "H304" => "H304 – Može biti smrtonosno ako se proguta i uđe u dišni sustav.",
            "H310" => "H310 – + H330 Smrtonosno u dodiru s kožom ili ako se udiše.",
            "H311" => "H311 – + H331 Otrovno u dodiru s kožom ili ako se udiše.",
            "H312" => "H312 – + H332 Štetno u dodiru s kožom ili ako se udiše.",
            "H314" => "H314 – Uzrokuje teške opekline kože i ozljede oka.",
            "H315" => "H315 – Nadražuje kožu.",
            "H317" => "H317 – Može izazvati alergijsku reakciju na koži.",
            "H318" => "H318 – Uzrokuje teške ozljede oka.",
            "H319" => "H319 – Uzrokuje jako nadraživanje oka.",
            "H330" => "H330 – Smrtonosno ako se udiše.",
            "H331" => "H331 – Otrovno ako se udiše.",
            "H332" => "H332 – Štetno ako se udiše.",
            "H334" => "H334 – Ako se udiše može izazvati simptome alergije ili astme ili poteškoće s disanjem.",
            "H335" => "H335 – Može nadražiti dišni sustav.",
            "H336" => "H336 – Može izazvati pospanost ili vrtoglavicu.",
            "H340" => "H340 – Može izazvati genetska oštećenja <navesti način izloženosti ako je potrebno>.",
            "H341" => "H341 – Sumnja na moguća genetska oštećenja <navesti način izloženosti ako je potrebno>.",
            "H350" => "H350 – Može uzrokovati rak <navesti način izloženosti ako je potrebno>.",
            "H351" => "H351 – Sumnja na moguće uzrokovanje raka <navesti način izloženosti ako je potrebno>.",
            "H360" => "H360 – Može štetno djelovati na plodnost ili naškoditi nerođenom djetetu <navesti konkretan učinak / način izloženosti>.",
            "H361" => "H361 – Sumnja na moguće štetno djelovanje na plodnost ili na nerođeno dijete <navesti konkretan učinak / način izloženosti>.",
            "H362" => "H362 – Može štetno djelovati na djecu koja se hrane majčinim mlijekom.",
            "H370" => "H370 – Uzrokuje oštećenje organa <navesti organ/e i eventualno način izloženosti>.",
            "H371" => "H371 – Može uzrokovati oštećenje organa <navesti organ/e i eventualno način izloženosti>.",
            "H372" => "H372 – Uzrokuje oštećenje organa pri produljenoj ili ponavljanoj izloženosti <navesti organ/e i način izloženosti>.",
            "H373" => "H373 – Može uzrokovati oštećenje organa pri produljenoj ili ponavljanoj izloženosti <navesti organ/e i način izloženosti>.",
            "H400" => "H400 – Vrlo otrovno za vodeni okoliš.",
            "H410" => "H410 – Vrlo otrovno za vodeni okoliš, s dugotrajnim učincima.",
            "H411" => "H411 – Otrovno za vodeni okoliš s dugotrajnim učincima.",
            "H412" => "H412 – Štetno za vodeni okoliš s dugotrajnim učincima.",
            "H413" => "H413 – Može uzrokovati dugotrajne štetne učinke na vodeni okoliš.",
            "H420" => "H420 – Štetno za zdravlje ljudi i okoliš zbog uništavanja ozona u višoj atmosferi.",
            "H350i" => "H350i – Može uzrokovati rak ako se udiše.",
            "H360F" => "H360F – Može štetno djelovati na plodnost.",
            "H360D" => "H360D – Može naškoditi nerođenom djetetu.",
            "H361f" => "H361f – Sumnja na moguće štetno djelovanje na plodnost.",
            "H361d" => "H361d – Sumnja na mogućnost štetnog djelovanja na nerođeno dijete.",
            "H360FD" => "H360FD – Može štetno djelovati na plodnost. Može naškoditi nerođenom djetetu.",
            "H361fd" => "H361fd – Sumnja na moguće štetno djelovanje na plodnost. Sumnja na mogućnost štetnog djelovanja na nerođeno dijete.",
            "H360Fd" => "H360Fd – Može štetno djelovati na plodnost. Sumnja na mogućnost štetnog djelovanja na nerođeno dijete.",
            "H360Df" => "H360Df – Može naškoditi nerođenom djetetu. Sumnja na moguće štetno djelovanje na plodnost.",
            "EUH001" => "EUH001 – Eksplozivno u suhom stanju.",
            "EUH006" => "EUH006 – Eksplozivno u dodiru ili bez dodira sa zrakom.",
            "EUH014" => "EUH014 – Reagira snažno s vodom.",
            "EUH018" => "EUH018 – Pri uporabi može nastati zapaljiva/eksplozivna smjesa pare i zraka.",
            "EUH019" => "EUH019 – Može stvoriti eksplozivne perokside.",
            "EUH029" => "EUH029 – U dodiru s vodom oslobađa otrovni plin.",
            "EUH031" => "EUH031 – U dodiru s kiselinama oslobađa otrovni plin.",
            "EUH032" => "EUH032 – U dodiru s kiselinama oslobađa vrlo otrovni plin.",
            "EUH044" => "EUH044 – Opasnost od eksplozije pri zagrijavanju u zatvorenom prostoru.",
            "EUH066" => "EUH066 – Ponavljani dodir može prouzročiti isušivanje ili pucanje kože.",
            "EUH070" => "EUH070 – Otrovno u dodiru s očima.",
            "EUH071" => "EUH071 – Nagrist će dišne putove.",
            "EUH201" => "EUH201 – Sadrži olovo. Ne koristiti na površinama koje djeca mogu žvakati.",
            "EUH201A"=> "EUH201A – Sadrži olovo.",
            "EUH202" => "EUH202 – Cijanokrilat. Oprez! Lijepi kožu i oči u nekoliko sekundi.",
            "EUH203" => "EUH203 – Sadrži krom (VI). Može izazvati alergijsku reakciju.",
            "EUH204" => "EUH204 – Sadrži izocijanate. Može izazvati alergijsku reakciju.",
            "EUH205" => "EUH205 – Sadrži epoksidne sastojke. Može izazvati alergijsku reakciju.",
            "EUH206" => "EUH206 – Oprez! Ne koristiti zajedno s drugim proizvodima. Može osloboditi opasne plinove (klorine).",
            "EUH207" => "EUH207 – Upozorenje! Sadrži kadmij. Za vrijeme uporabe nastaju opasne pare.",
            "EUH208" => "EUH208 – Sadrži senzibilizirajuću tvar; može izazvati alergijsku reakciju.",
            "EUH210" => "EUH210 – Sigurnosno-tehnički list dostupan na zahtjev.",
            "EUH211" => "EUH211 – Udisanje raspršenih kapljica može izazvati alergijske reakcije.",
            "EUH212" => "EUH212 – Udisanje prašine može izazvati alergijske reakcije.",
            "EUH401" => "EUH401 – Primjenjivati u skladu s uputama kako bi se izbjegli rizici za ljude i okoliš.",
        ];
    }
}
