<?php

namespace App\Enums;

class PrecautionaryStatement
{
    public static function list(): array
    {
        return [
            "P101" => "P101 – Ako je potreban savjet liječnika, pokazati spremnik ili naljepnicu.",
            "P102" => "P102 – Čuvati izvan dohvata djece.",
            "P103" => "P103 – Prije uporabe pročitati naljepnicu.",

            // PREVENCIJA
            "P201" => "P201 – Pribaviti posebne upute prije uporabe.",
            "P202" => "P202 – Ne upotrebljavati prije nego što se pročitaju i shvate sve sigurnosne mjere.",
            "P210" => "P210 – Čuvati od topline, vrućih površina, iskri, otvorenog plamena i drugih izvora paljenja. Ne pušiti.",
            "P211" => "P211 – Ne raspršivati prema otvorenom plamenu ili drugom izvoru paljenja.",
            "P220" => "P220 – Držati/pohraniti odvojeno od odjeće/.../zapaljivih materijala.",
            "P221" => "P221 – Poduzeti mjere protiv statičkog elektriciteta.",
            "P222" => "P222 – Ne dopustiti dodir sa zrakom.",
            "P223" => "P223 – Ne dopustiti dodir s vodom.",
            "P230" => "P230 – Držati vlažno …",
            "P231" => "P231 – Rukovati u inertnoj atmosferi.",
            "P231+P232" => "P231+P232 – Rukovati u inertnoj atmosferi. Zaštititi od vlage.",
            "P233" => "P233 – Spremnik dobro zatvoren.",
            "P234" => "P234 – Čuvati samo u originalnom spremniku.",
            "P235" => "P235 – Čuvati na hladnom.",
            "P235+P410" => "P235+P410 – Čuvati na hladnom. Zaštititi od sunčevog zračenja.",
            "P240" => "P240 – Uzemljiti/izjednačiti spremnik i opremu.",
            "P241" => "P241 – Koristiti električnu/ventilacijsku/rasvjetnu opremu otpornu na eksploziju.",
            "P242" => "P242 – Koristiti samo alate koji ne stvaraju iskre.",
            "P243" => "P243 – Poduzeti mjere protiv stvaranja statičkog elektriciteta.",
            "P244" => "P244 – Oprema s regulacijom tlaka: redovito provjeravati i održavati.",
            "P250" => "P250 – Ne podvrgavati trljanju/udarima/trenju.",
            "P260" => "P260 – Ne udisati prašinu/dim/plin/maglu/pare/raspršene kapljice.",
            "P261" => "P261 – Izbjegavati udisanje prašine/dima/plina/magle/para/raspršenih kapljica.",
            "P262" => "P262 – Ne dopustiti dodir s očima, kožom ili odjećom.",
            "P263" => "P263 – Izbjegavati kontakt tijekom trudnoće/dojenja.",
            "P264" => "P264 – Temeljito oprati ruke nakon uporabe.",
            "P270" => "P270 – Ne jesti, piti ili pušiti pri rukovanju proizvodom.",
            "P271" => "P271 – Koristiti samo na otvorenom ili u dobro prozračenom prostoru.",
            "P272" => "P272 – Kontaminirana radna odjeća ne smije napuštati radno mjesto.",
            "P273" => "P273 – Izbjegavati ispuštanje u okoliš.",
            "P280" => "P280 – Nositi zaštitne rukavice/zaštitnu odjeću/zaštitu za oči/zaštitu za lice.",
            "P281" => "P281 – Koristiti propisanu osobnu zaštitnu opremu.",
            "P282" => "P282 – Nositi zaštitu od hladnoće.",
            "P283" => "P283 – Nositi zaštitnu odjeću otpornu na plamen.",
            "P284" => "P284 – Nositi zaštitu dišnog sustava.",
            "P285" => "P285 – U prostoru s nedostatnim prozračivanjem koristiti zaštitu dišnog sustava.",

            // REAKCIJA
            "P301" => "P301 – AKO SE PROGUTA:",
            "P301+P310" => "P301+P310 – AKO SE PROGUTA: Odmah nazvati CENTAR ZA TROVANJA/liječnika.",
            "P301+P312" => "P301+P312 – AKO SE PROGUTA: Ako se ne osjećate dobro, nazvati CENTAR ZA TROVANJA/liječnika.",
            "P301+P330+P331" => "P301+P330+P331 – AKO SE PROGUTA: Isprati usta. NE izazivati povraćanje.",
            "P302" => "P302 – AKO DOSPIJE NA KOŽU:",
            "P302+P334" => "P302+P334 – AKO NA KOŽU DOSPIJE OHLAĐENI PLIN: Zagrijati zahvaćeno područje mlakom vodom.",
            "P302+P350" => "P302+P350 – AKO NA KOŽU: Nježno oprati s mnogo vode i sapuna.",
            "P302+P352" => "P302+P352 – AKO NA KOŽU: Oprati s mnogo vode/sapuna.",
            "P303" => "P303 – AKO NA KOŽU (ili kosu):",
            "P303+P361+P353" => "P303+P361+P353 – AKO NA KOŽU (ili kosu): Odmah skinuti svu kontaminiranu odjeću. Isprati kožu vodom/tušem.",
            "P304" => "P304 – AKO SE UDIŠE:",
            "P304+P340" => "P304+P340 – AKO SE UDIŠE: Izvesti osobu na svježi zrak i držati u položaju pogodnom za disanje.",
            "P304+P341" => "P304+P341 – AKO SE UDIŠE: U slučaju poteškoća s disanjem, izvesti na svježi zrak i držati mirno.",
            "P305" => "P305 – AKO DOSPIJE U OČI:",
            "P305+P351+P338" => "P305+P351+P338 – AKO U OČI: Oprezno ispirati vodom nekoliko minuta. Izvaditi kontaktne leće ako postoje i ako se lako uklanjaju. Nastaviti ispirati.",
            "P306" => "P306 – AKO NA ODJEĆI:",
            "P306+P360" => "P306+P360 – AKO NA ODJEĆI: Odmah isprati kontaminiranu odjeću i kožu prije skidanja.",
            "P307" => "P307 – AKO izložen:",
            "P307+P311" => "P307+P311 – AKO izložen: Nazvati CENTAR ZA TROVANJA/liječnika.",
            "P308" => "P308 – AKO izložen ili zabrinut:",
            "P308+P313" => "P308+P313 – AKO izložen ili zabrinut: Zatražiti savjet/pomoć liječnika.",
            "P309" => "P309 – U slučaju izloženosti ili ako se ne osjećate dobro:",
            "P309+P311" => "P309+P311 – U slučaju izloženosti ili ako se ne osjećate dobro: Nazvati CENTAR ZA TROVANJA/liječnika.",
            "P310" => "P310 – Odmah nazvati CENTAR ZA TROVANJA/liječnika.",
            "P311" => "P311 – Nazvati CENTAR ZA TROVANJA/liječnika.",
            "P312" => "P312 – Ako se ne osjećate dobro, nazvati CENTAR ZA TROVANJA/liječnika.",
            "P313" => "P313 – Zatražiti savjet/pomoć liječnika.",
            "P314" => "P314 – Ako se ne osjećate dobro, potražiti liječničku pomoć.",
            "P315" => "P315 – Odmah potražiti liječničku pomoć.",
            "P320" => "P320 – Specifičan tretman hitnog djelovanja potreban (vidi na naljepnici).",
            "P321" => "P321 – Specifičan tretman (vidi na naljepnici).",
            "P322" => "P322 – Specifične mjere (vidi na naljepnici).",
            "P330" => "P330 – Isprati usta.",
            "P331" => "P331 – NE izazivati povraćanje.",
            "P332" => "P332 – Ako se pojavi nadražaj kože:",
            "P332+P313" => "P332+P313 – Ako se pojavi nadražaj kože: Zatražiti savjet/pomoć liječnika.",
            "P333" => "P333 – Ako se pojavi osip na koži:",
            "P333+P313" => "P333+P313 – Ako se pojavi osip na koži: Zatražiti savjet/pomoć liječnika.",
            "P334" => "P334 – Uroniti u hladnu vodu/obložiti vlažnim oblozima.",
            "P335" => "P335 – Pažljivo ukloniti rasute čestice s kože.",
            "P335+P334" => "P335+P334 – Ukloniti rasute čestice s kože. Uroniti u hladnu vodu/oblozi.",
            "P336" => "P336 – Odmrznuti smrznuto područje vodom. Ne trljati zahvaćeno područje.",
            "P337" => "P337 – Ako nadražaj oka ne prestaje:",
            "P337+P313" => "P337+P313 – Ako nadražaj oka ne prestaje: Zatražiti savjet/pomoć liječnika.",
            "P338" => "P338 – Izvaditi kontaktne leće ako se lako uklanjaju. Nastaviti ispirati.",
            "P340" => "P340 – Izvesti na svježi zrak i držati u položaju pogodnom za disanje.",
            "P341" => "P341 – U slučaju poteškoća s disanjem: Izvesti na svježi zrak i držati mirno.",
            "P351" => "P351 – Oprezno ispirati vodom nekoliko minuta.",
            "P352" => "P352 – Oprati s mnogo vode/sapuna.",
            "P353" => "P353 – Isprati kožu vodom/tušem.",
            "P360" => "P360 – Odmah isprati kontaminiranu odjeću i kožu prije skidanja.",
            "P361" => "P361 – Odmah skinuti svu kontaminiranu odjeću.",
            "P361+P364" => "P361+P364 – Skinuti kontaminiranu odjeću i oprati prije ponovne uporabe.",
            "P362" => "P362 – Skinuti kontaminiranu odjeću.",
            "P362+P364" => "P362+P364 – Skinuti kontaminiranu odjeću i oprati prije ponovne uporabe.",
            "P363" => "P363 – Oprati kontaminiranu odjeću prije ponovne uporabe.",
            "P364" => "P364 – Oprati kontaminiranu odjeću prije ponovne uporabe.",
            "P370" => "P370 – U slučaju požara:",
            "P370+P376" => "P370+P376 – U slučaju požara: Zaustaviti curenje ako je sigurno učiniti.",
            "P370+P378" => "P370+P378 – U slučaju požara: Koristiti odgovarajući medij za gašenje.",
            "P370+P380" => "P370+P380 – U slučaju požara: Evakuirati područje.",
            "P371" => "P371 – U velikom požaru i velikim količinama:",
            "P371+P380+P375" => "P371+P380+P375 – U velikom požaru i velikim količinama: Evakuirati područje. Gasiti iz daljine zbog rizika od eksplozije.",
            "P372" => "P372 – Opasnost od eksplozije u slučaju požara.",
            "P373" => "P373 – NE gasiti požar ako plamen dopire do eksploziva.",
            "P374" => "P374 – Gasiti požar prema standardnim postupcima za kemikalije.",

            // SKLADIŠTENJE
            "P401" => "P401 – Pohraniti prema propisima.",
            "P402" => "P402 – Čuvati na suhom mjestu.",
            "P402+P404" => "P402+P404 – Čuvati na suhom mjestu. Čuvati u zatvorenom spremniku.",
            "P403" => "P403 – Čuvati na dobro prozračenom mjestu.",
            "P403+P233" => "P403+P233 – Čuvati na dobro prozračenom mjestu. Spremnik dobro zatvoren.",
            "P403+P235" => "P403+P235 – Čuvati na dobro prozračenom mjestu. Čuvati na hladnom.",
            "P404" => "P404 – Čuvati u zatvorenom spremniku.",
            "P405" => "P405 – Pohraniti pod ključem.",
            "P406" => "P406 – Čuvati u korozijski otpornom spremniku s otpornom unutarnjom oblogom.",
            "P407" => "P407 – Ostavljati prostor između podova/paleta.",
            "P410" => "P410 – Zaštititi od sunčevog zračenja.",
            "P410+P403" => "P410+P403 – Zaštititi od sunčevog zračenja. Čuvati na dobro prozračenom mjestu.",
            "P410+P412" => "P410+P412 – Zaštititi od sunčevog zračenja. Ne izlagati temperaturama iznad 50 °C/122 °F.",
            "P411" => "P411 – Pohraniti na temperaturama ne višim od … °C.",
            "P411+P235" => "P411+P235 – Pohraniti na temperaturama ne višim od … °C. Čuvati na hladnom.",
            "P412" => "P412 – Ne izlagati temperaturama iznad 50 °C/122 °F.",
            "P413" => "P413 – Pohraniti velike količine na dobro prozračenom mjestu.",
            "P414" => "P414 – Držati odvojeno od nekompatibilnih materijala.",
            "P420" => "P420 – Čuvati odvojeno.",
            "P422" => "P422 – Pohraniti sadržaj pod …",

            // ODLAGANJE
            "P501" => "P501 – Odložiti sadržaj/spremnik u skladu s lokalnim/regionalnim/nacionalnim/međunarodnim propisima.",
        ];
    }
}